=== halbich/Pogamut3/Main/PogamutUT2004/src/gb2004/messages/GBMessages.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Document   : GBMessages.dtd
    Created on : 17. march 2008, 11:30
    Author     : Jakub Gemrot
    Description:
        Defines the DTD for Gamebots messages that are sent/received by the client/gamebots.

    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/GBMessages.dtd
-->

<!--
	The 'messages' consists of three things:
 	1) 'settings' - configuration for JavaClassesGenerator.xsl and FlexGenerator.xsl
 	2) 'infomessages' - definitions of messages that the Gamebots is sending to the Agent
 	3) 'commands' - definitions of messages that the Agent may sent to Gamebots
-->
<!ELEMENT messages (settings, infomessages, commands)>

<!--
	The 'settings' has two parts:
	1) 'javasettings' - configuration for JavaClassesGenerator.xsl
	2) 'jflexsettings' - configuration for FlexGenerator.xsl
-->
<!ELEMENT settings (javasettings, jflexsettings)>

<!--
	The 'javasettings' contains this:
	1) 'javapackageinfomessages' - name of the package where all info messages resides
	2) 'javapackagecommands' - name of the package where all commands resides
	3) 'javaimport' - what packages has to be imported for every info messages/command class
	              - those imports are added to produced java classes (like NavPoint.java, Jump.java, etc.)
-->	
<!ELEMENT javasettings (javapackageinfomessages, javapackagecommands, javaimport*)>
<!ELEMENT javapackageinfomessages (#PCDATA)>
<!ATTLIST javapackageinfomessages package CDATA #REQUIRED>
<!ELEMENT javapackagecommands (#PCDATA)>
<!ATTLIST javapackagecommands package CDATA #REQUIRED>
<!ELEMENT javaimport (#PCDATA)>
<!ATTLIST javaimport import CDATA #REQUIRED>

<!--
	The 'jflexsettings' contains:
	1) 'jflexpackage' - name of the package where Yylex resides
					- directive 'package' of the flex file
	2) 'javaimport' - packages that should be imported for the Yylex
-->				  					
<!ELEMENT jflexsettings (jflexpackage, javaimport*)>
<!ELEMENT jflexpackage (#PCDATA)>
<!ATTLIST jflexpackage package CDATA #REQUIRED>

<!ELEMENT infomessages (messageobject+)>
<!ELEMENT commands (commandobject+)>

<!--
	The 'messageobject' is defined by:
	1) one ore more 'groups'
		- this is telling you whether the message object is for Bot or Server connection
		- it also tells us where the message should appear in the GameBots documentation (Bot/Server messages)
	2) 'documentation'
		- what will appear as documentation in java / GameBots documentation
	3) possibly some 'annotations'
		- this is a hook where you can provide annotations for the result java class
	4) 'implements'
		- you may define custom interfaces for the generated java classes (these interfaces will be included in all categories of ObjectUpdates)
		- these interfaces will be added to all combinations of classcategory/classtype
	5) 'interface'
	    - even though it is nice that 'implements' allows you to add interfaces to a message, it won't suffice you in the case of ObjectUpdates type of message
	      such messages are split into three categories of object static/local/shared and you will need to finegrain the "implements" element
	      so different interfaces will be included into different categories (classes)
	    - allows you to specify who has to truly "implement" the interface (which category)
	6) 'property'
		- this describes java fields of the class and the message
		- this fields are reflected both by JavaClassesGenerator.xslt and FlexGenerator.xslt
		- JavaClassesGenerator.xslt creates java fields + possibly update method (for ObjectUpdate type of messageobject)
		- FlexParser writes a script to parse this field
		- IMPORTANT: the name of the property must match (case-sensitive!) the name of the attribute of appropriate message from GameBots
	7) 'extra'
		- here we've got hooks to add java / jflex custom code for java classes / flex script
	======
	The messageobject must have those attributes:
	1) 'name'
		- the name of the message (used as name for java class)
		- must be correct java variable identifier name
	2) 'extends'
		- name of the java class the message extends (should be InfoObject)
	3) 'message'
		- identifier of the message from GameBots protocal (like 'INV')
		- used by FlexParser.xslt to produce correct flex script (to correctly recognize the
		   category of incoming message)
	4) 'type'
		- describes the type of message, what it represents
		-  1) 'Batch' - those messages comes usually in the beginning of the connection
		                to provide informations about map (like items, navpoints,...)
		              - Batch is translated (to Java) as IWorldEvent, IWorldViewEvent  
		   2) 'Event' - asynchronous messages like 'Hit the wall', 'Got hit', ...
		   			  - Event is translated (to Java) as IWorldEvent, IWorldViewEvent
		   3) 'ObjectUpdate' - events about abstract or concrete objects in the worlds
		   					 - concrete objects are Players, NavPoints, etc.
		   					 - abstract objects are Scores, AutoTraceRay, etc.
		   					 - ObjectUpdate is translated (to Java) as IWorldEvent, IWorldObject, IWorldObjectUpdateEvent				
-->				
<!ELEMENT messageobject (gbpackage*, group+, documentation, annotation*, implements?, interface*, property*, extra?)>
<!ATTLIST messageobject name CDATA #REQUIRED>
<!ATTLIST messageobject extends CDATA #REQUIRED>
<!ATTLIST messageobject message CDATA #REQUIRED>
<!ATTLIST messageobject type (Batch|Event|ObjectUpdate) #IMPLIED>

<!--
	The 'commandobject' is defined by:
	1) one ore more 'groups'
		- this is telling you whether the message object is for Bot or Server connection
		- it also tells us where the message should appear in the GameBots documentation (Bot/Server messages)
	2) 'documentation'
		- what will appear as documentation in java / GameBots documentation
	3) possibly some 'annotations'
		- this is a hook where you can provide annotations for the result java class
	4) 'implements'
		- you may define custom interfaces for the generated java classes
	5) 'property'(ies)
		- this describes java fields of the class and the message
		- this fields are reflected both by JavaClassesGenerator.xslt and FlexGenerator.xslt
		- JavaClassesGenerator.xslt creates java fields + possibly update method (for ObjectUpdate type of messageobject)
		- FlexParser writes a script to parse this field
		- IMPORTANT: the name of the property must match (case-sensitive!) the name of the attribute of appropriate message from GameBots
	6) 'extra'
		- here we've got hooks to add java / jflex custom code for java classes / flex script
	======
	The messageobject must have those attributes:
	1) 'command'
		- the name of the message (used as name for java class)
		- must be correct java variable identificator name
	2) 'extends'
		- name of the java class the message extends (should be descendant of the InfoObject)
	3) 'name'
		- identifier of the message from GameBots protocol (like 'INV')
		- used by FlexParser.xslt to produce correct flex script (to correctly recognize the category of incoming message)
	4) 'type'
		- describes the type of message, what it represents
		- 1) 'Configure' - category of commands that configures something
		                 - like AddInventory, ...  
		  2) 'Control' - commands for the bot usually
		  			   - like run to, shoot, etc.
		  3) 'Info' - commands requesting some informations
		  		    - like give me list of current players
-->	
<!ELEMENT commandobject (gbpackage*, group+, documentation, annotation*, implements?, property*, extra?)>
<!ATTLIST commandobject command CDATA #REQUIRED>
<!ATTLIST commandobject extends CDATA #REQUIRED>
<!ATTLIST commandobject name CDATA #REQUIRED>
<!ATTLIST commandobject type (Configure|Control|Info) #IMPLIED>

<!ELEMENT group (#PCDATA)>
<!ATTLIST group name (Bot|Server|Observer) #IMPLIED>

<!ELEMENT annotation (#PCDATA)>
<!ATTLIST annotation name CDATA #REQUIRED>

<!ELEMENT implements (#PCDATA)>
<!ATTLIST implements interfaces CDATA #REQUIRED>

<!ELEMENT interface (classcategory|classtype)*>
<!ATTLIST interface name CDATA #REQUIRED> 

<!ELEMENT documentation (#PCDATA)>

<!--
	The messageproperty has three REQUIRED attributes (one has default value so it does not need to be present):
	1) name     ... name of the property as it appears in the GameBots protocol
	            ... YOU MUST NOT DECLARE PROPERTY WITH NAME 'SimTime' 
	2) type     ... Java type of the field in the Java class of the message
	3) category ... it is either 'static', 'local' or 'shared' (or 'all')
	                static -> static fields are never updated, once initialized they won't be overridden by future messages
	                          this represents information that are static for a chosen environment (e.g., navpoint's neighbours)
	                local  -> the local properties are subjectively perceived by the bot (e.g., some navpoint or player is visible)
	                	   -> DEFAULT CATEGORY
	                shared -> shared information are data that are objectively perceived by any bot regardless his position or mind state
	                          (e.g., item is spawned at location ... this information is different from the information "item is visible" becuase
	                                 it does not need the subjective context of the bot location, regardless where the bot stands, the item is or is not
	                                 spawned at certain location)
	                all    -> specific category that is saying that the value must be present in static/local/shared parts 
	                          and is static
	                       -> if you are DECLARING property WITH NAME 'Id' YOU MUST SET ITS CATEGORY TO 'all'
	            ... no meaning for COMMANDOBJECTs
	Then there are optional properties:
	1) default  ... default value of the property if it's not specified (be it a command or infoobject)
	2) nullable ... whether the property may be set to "null" (has sense only for messageobjects & category local/shared/all), 
	                used in updates
				... if appears it must be false (because default is true)
	3) jflex    ... if specified must be 'no' then it won't appear in the parser + not in toString() method (recursion in NavPoint / Item is around the corner :)
	            ... no meaning for COMMANDOBJECTs
	4) jason    ... if specified must be 'yes' then it won't appear in the toJsonLiteral() method
	            ... no meaning for COMMANDOBJECTs          
    5) optional ... whether the property is optional for the object (i.e., messageobject == exported / commandobject == expected by GB2004)
-->
<!ELEMENT property (documentation, extra?)>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property type CDATA #REQUIRED>
<!ATTLIST property category (static|local|shared|all) 'local'>
<!ATTLIST property default CDATA #IMPLIED>
<!ATTLIST property nullable (false) #IMPLIED>
<!ATTLIST property optional (true) #IMPLIED>

<!-- 
	whether to include into jflex file, default is 'yes', but this is not allowed,
	if attribute is declared - it has to be 'no'
	also if this is declared, it won't appear in the GB API Documentation
-->
<!ATTLIST property jflex (no) #IMPLIED>
<!ATTLIST property jason (yes) #IMPLIED>  
 
<!ELEMENT extra (code?)>

<!ELEMENT code ((java*,yylex?)|(yylex?, java*))>

<!-- 
	May contain two things:
	 1) #PCDATA - custom java code placed directly to all generated class (in the case of 'ObjectUpdate' this code is placed to all three parts of the object static/shared/local)
	 2) 'javaimport' - additional custom imports for the generated class 
-->
<!ELEMENT java (#PCDATA|javaimport|javapart)*>

<!-- 
	May contain custom code that is placed to the concrete part of message depending on the children elements 'classcategory' and 'classtype'.
	Every javapart MUST HAVE at least one <classcategory name="..."/> child element and at least one <classtype name="..."/> child element.
	The body of the <javapart> contains actual java code that is pasted to the conrete class declaration of the message. 
	Note that every <javapart> element may contain arbitrary number of <classcategory ... /> and <classtype ... /> children elements allowing
	you to precisly specify in which classes the custom java code should appear in.
	
	NOT RELEVANT TO COMMANDOBJECT!!!
-->
<!ELEMENT javapart (#PCDATA|javaimport|classcategory|classtype)*>

<!--	
	Contains name of the category of the class where the custom java code should be generated into (must be used together with <classtype ... > element).
	
	base		... 
	composite	... 
	local		... 
	shared		... 
	static		... 
-->
<!ELEMENT classcategory EMPTY>
<!ATTLIST classcategory name (all|base|composite|local|shared|static) #REQUIRED>

<!--	
	Contains name of the type of the class where the custom java code should be generated into (must be used together with <classcategory ... > element).
	'abstract'      -> 
	'message'       -> 
	'impl'          -> 	
-->
<!ELEMENT classtype EMPTY>
<!ATTLIST classtype name (all|abstract|message|impl) #REQUIRED>


<!-- CURRENTLY NOT USED! Reserved for future... -->
<!ELEMENT yylex (#PCDATA)>

<!ELEMENT gbpackage EMPTY>
<!ATTLIST gbpackage name CDATA #REQUIRED>

=== halbich/Pogamut3/Main/PogamutUT2004/src/gb2004/messages/gbinfomessages/InitedMessage.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE messageobject SYSTEM "../GBMessages.dtd">

<messageobject extends="InfoMessage" message="INITED" name="InitedMessage" type="ObjectUpdate">
   <gbpackage name="GameBots2004"/>
   <gbpackage name="GBScenario"/>
   <gbpackage name="GameBotsAnim"/>
   <gbpackage name="GameBotsUE2"/>
   <gbpackage name="GBEmohawk"/>
   <group name="Bot"/>
   <documentation>
		Asynchronous message. Sent after succesfull init command (so usually just once). 
		Holds many attributes of the bots like speed, id starting and max health, etc.
		Some attributes are not used due to GameBots mechanics.
	</documentation>
   <!-- List of all properties of this message. !-->
   <property name="BotId" type="UnrealId" category="local">
      <documentation>
			A unique unreal Id of the new bot.
		</documentation>
   </property>
   <property name="HealthStart" type="int" category="local">
      <documentation>
			Bot will always start with this health amount (usually 100). 
		</documentation>
   </property>
   <property name="HealthFull" type="int" category="local">
      <documentation>
			Full health of the bot (usually 100).
		</documentation>
   </property>
   <property name="HealthMax" type="int" category="local">
      <documentation>
			Maximum health of the bot (default 199).
		</documentation>
   </property>
   <property name="AdrenalineStart" type="double" category="local">
      <documentation>
			Amount of adrenaline at the start. Usually 0.
		</documentation>
   </property>
   <property name="AdrenalineMax" type="double" category="local">
      <documentation>
			Maxium amount of the adrenaline. Usually 100 (this can trigger the combos).
		</documentation>
   </property>
   <property name="ShieldStrengthStart" type="int" category="local">
      <documentation>
			Starting strength of the bot armor (usually 0).
		</documentation>
   </property>
   <property name="ShieldStrengthMax" type="int" category="local">
      <documentation>
			Maximum strength of the bot armor (usually 150).
		</documentation>
   </property>
   <property name="MaxMultiJump" type="int" category="local">
      <documentation>
			Maximum amount of succesing jumps. Currently limited to double jump in GB.
		</documentation>
   </property>
   <property name="DamageScaling" type="double" category="local">
      <documentation>
			Damage scaling for this bot. (he will deal reduced damage depending on the setting).
		</documentation>
   </property>
   <property name="GroundSpeed" type="double" category="local">
      <documentation>
			Groundspeed of the bot (on the ground). Default 440.
		</documentation>
   </property>
   <property name="WaterSpeed" type="double" category="local">
      <documentation>
			Waterspeed of the bot (in the water).
		</documentation>
   </property>
   <property name="AirSpeed" type="double" category="local">
      <documentation>
			AirSpeed of the bot (in the air).
		</documentation>
   </property>
   <property name="LadderSpeed" type="double" category="local">
      <documentation>
			Ladderspeed of the bot (on the ladder).
		</documentation>
   </property>
   <property name="AccelRate" type="double" category="local">
      <documentation>
			Accelartion rate of this bot. How fast he accelerates.
		</documentation>
   </property>
   <property name="JumpZ" type="double" category="local">
      <documentation>
			 Bot Jump's Z boost.
		</documentation>
   </property>
   <property name="MultiJumpBoost" type="double" category="local">
      <documentation>
			Not used in GB.
		</documentation>
   </property>
   <property name="MaxFallSpeed" type="double" category="local">
      <documentation>
			 Max fall speed of the bot.
		</documentation>
   </property>
   <property name="DodgeSpeedFactor" type="double" category="local">
      <documentation>
			Dodge speed factor.
		</documentation>
   </property>
   <property name="DodgeSpeedZ" type="double" category="local">
      <documentation>
			Dodge jump Z boost of the bot. 
		</documentation>
   </property>
   <property name="AirControl" type="double" category="local">
      <documentation>
			How well can be the bot controlled in the air (ranges from 0 to 1).
		</documentation>
   </property>
   <!-- Extra information used by different modules of the Pogamut platform. !--><extra>
      <code/>
   </extra>
</messageobject>

=== halbich/Pogamut3/Main/PogamutUT2004/src/gb2004/messages/gbcommands/GetItemCategory.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE commandobject SYSTEM "../GBMessages.dtd">

<commandobject command="GETITC" extends="CommandMessage" name="GetItemCategory" type="Info">
   <gbpackage name="GameBots2004"/>
   <gbpackage name="GBScenario"/>
   <gbpackage name="GameBotsAnim"/>
   <gbpackage name="GameBotsUE2"/>
   <gbpackage name="GBEmohawk"/>
   <group name="Bot"/>
   <group name="Observer"/>
   <documentation>
		Request to export item category by ITC message. Will respond with ITC message.
	</documentation>
   <!-- List of all properties of this command. !--><property name="Type" type="String">
      <documentation>
			Class of the item we want to export ITC message for. Must be pickup class (e.g.
			xWeapons.FlakCannonPickup).
		</documentation>
   </property>
   <!-- Extra information used by different modules of the Pogamut platform. !--><extra>
      <code/>
   </extra>
</commandobject>

=== halbich/Pogamut3/Main/PogamutUT2004/src/gb2004/messages/gbinfomessages/MapList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE messageobject SYSTEM "../GBMessages.dtd">

<messageobject extends="InfoMessage" message="IMAP" name="MapList" type="Batch">
   <gbpackage name="GameBots2004"/>
   <gbpackage name="GBScenario"/>
   <gbpackage name="GameBotsAnim"/>
   <gbpackage name="GameBotsUE2"/>
   <gbpackage name="GBEmohawk"/>
   <group name="Server"/>
   <documentation>
		Info batch message. Starts with SMAP message, ends with EMAP
		message. Hold information about available maps on the server
		(maps to which we can change the game).
	</documentation>
        <implements interfaces="cz.cuni.amis.pogamut.unreal.communication.messages.gbinfomessages.IMapList"/>
   <!-- List of all properties of this message. !--><property name="Name" type="String" category="shared">
      <documentation>
			Name of one map in map list on the server.
		</documentation>
   </property>
   <!-- Extra information used by different modules of the Pogamut platform. !--><extra>
      <code/>
   </extra>
</messageobject>

=== halbich/Pogamut3/Main/PogamutUT2004/src/gb2004/messages/gbinfomessages/Player.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE messageobject SYSTEM "../GBMessages.dtd">

<messageobject extends="InfoMessage" message="PLR" name="Player" type="ObjectUpdate">
   <gbpackage name="GameBots2004"/>
   <gbpackage name="GBScenario"/>
   <gbpackage name="GameBotsAnim"/>
   <gbpackage name="GameBotsUE2"/>
   <gbpackage name="GBEmohawk"/>
   <group name="Bot"/>
   <group name="Server"/>
   <group name="Observer"/>
   <documentation>
		Synchronous message. Contains information about other players in
		the game, like their current velocity, position, weapon and
		reachability. Only reports those players that are visible.
		(within field of view and not occluded).
	</documentation>
   <!-- List of interfaces it implements -->
   <!--  cz.cuni.amis.pogamut.unreal.communication.messages.gbinfomessages.Player-->
   <interface name="IPerson">
   	<classcategory name="base" />
   	<classtype name="abstract" />
   </interface>
   <interface name="cz.cuni.amis.pogamut.unreal.communication.messages.gbinfomessages.IPlayer">
    <classcategory name="base" />
   	<classtype name="abstract" />
   </interface>
   <interface name="IGBViewable">
		<classcategory name="base" />
		<classtype name="abstract" />
   </interface>
   <interface name="ILocalGBViewable">
   		<classcategory name="local" />
   		<classtype name="abstract" />
   </interface>
   
   <!-- List of all properties of this message. !-->
   <property name="Id" type="UnrealId" category="all" jason="yes">
      <documentation>Unique Id of the player.</documentation>
   </property>
   <property name="Jmx" type="String" category="local">
      <documentation>
			Exported just for control server. Holds jmx address we need to connect to
            when we want to debug our bot.
		</documentation>
   </property>
   <property name="Name" type="String" category="shared" jason="yes">
      <documentation>
			Human readable name of the player.
		</documentation>
   </property>
   <property name="Spectator" type="Boolean" category="shared"  default="false">
      <documentation>
			Whether this player is in SPECTATE mode. Humans can change the mode during runtime!
		</documentation>
   </property>
   <property name="Action" type="String" category="shared">
      <documentation>
			Atomic action this bot is doing (BDI).
		</documentation>
   </property>
   <property name="Visible" type="boolean" category="local" default="true" jason="yes">
      <documentation>
            If the player is in the field of view of the bot.
        </documentation>
   </property>
   <property name="Rotation" type="Rotation" category="shared">
      <documentation>
			Which direction the player is facing in absolute terms.
		</documentation>
   </property>
   <property name="Location" type="Location" category="shared" nullable="false" jason="yes">
      <documentation>
			An absolute location of the player within the map.
		</documentation>
   </property>
   <property name="Velocity" type="Velocity" category="shared">
      <documentation>
			Absolute velocity of the player as a vector of movement per one
			game second.
		</documentation>
   </property>
   <property name="Team" type="int" category="shared" jason="yes">
      <documentation>
			What team the player is on. 255 is no team. 0-3 are red,
			blue, green, gold in that order.
		</documentation>
   </property>
   <property name="Weapon" type="String" category="shared">
      <documentation>
			Class of the weapon the player is holding. Weapon strings to
			look for include: "AssaultRifle", "ShieldGun", "FlakCannon",
			"BioRifle", "ShockRifle", "LinkGun", "SniperRifle",
			"RocketLauncher", "Minigun", "LightingGun", "Translocator".
			TODO: Look if this is all.
		</documentation>
   </property>
   <property name="Crouched" type="boolean" category="shared">
      <documentation>
			True if the bot is crouched.
		</documentation>
   </property>   
   <property name="Firing" type="int" category="shared">
      <documentation>
			0 means is not firing, 1 - firing in primary mode, 2 -
			firing in secondary mode (alt firing).
		</documentation>
   </property>
   <property name="EmotLeft" type="String" category="shared">
      <documentation>
			For UE2. Holds left emoticon of the bot, "None" means none set.
		</documentation>
   </property>
   <property name="EmotCenter" type="String" category="shared">
      <documentation>
			For UE2. Holds center emoticon of the bot, "None" means none set.
		</documentation>
   </property>
   <property name="EmotRight" type="String" category="shared">
      <documentation>
			For UE2. Holds right emoticon of the bot, "None" means none set.
		</documentation>
   </property>
   <property name="Bubble" type="String" category="shared">
      <documentation>
			For UE2. Holds the bubble of the emoticon of the bot, "None" means none set.
		</documentation>
   </property>
   <property name="Anim" type="String" category="shared">
      <documentation>
			For UE2. Current played animation of the bot.
		</documentation>
   </property>  
   <!-- Extra information used by different modules of the Pogamut platform. !--><extra>
      <code/>
   </extra>
</messageobject>

=== halbich/Pogamut3/Main/PogamutUT2004/src/gb2004/messages/gbcommands/ConfigurationObserver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE commandobject SYSTEM "../GBMessages.dtd">

<commandobject command="CONF" extends="CommandMessage" name="ConfigurationObserver"
               type="Configure">
   <gbpackage name="GameBots2004"/>
   <gbpackage name="GBScenario"/>
   <gbpackage name="GameBotsAnim"/>
   <group name="Observer"/>
   <documentation>
		Configures various attributes of the observer. You can include several of the parameters.
		The state of options you don't specify will remain unchanged.
    </documentation>
   <property name="UpdateTime" type="double">
      <documentation>
			The frequency (in seconds) you will receive updates from the observer.
		</documentation>
   </property>
   <property name="Update" type="double">
      <documentation>
			The frequency (in seconds) you will receive updates from the observer. Same as UpdateTime.
		</documentation>
   </property>
   <property name="Game" type="boolean">
      <documentation>
			Whether to send game-related messages with every update.
			Affects the following messages: NFO, PLR.
		</documentation>
   </property>
   <property name="Self" type="boolean">
      <documentation>
			Whether to send messages about the observed player with every update.
			Affects the following messages: SLF, MYINV.
		</documentation>
   </property>
   <property name="See" type="boolean">
      <documentation>
			Whether to send messages about what the observed player sees with every update.
			Affects the following messages: PLR, INV, NAV, MOV, PRJ, VEH.
		</documentation>
   </property>
   <property name="Special" type="boolean">
      <documentation>
			Whether to send messages about special objects on the map with every update.
			Affects the following messages: FLG, BOM, DOM.
		</documentation>
   </property>
   <property name="All" type="boolean">
      <documentation>
			Toggles sending all messages with every update.
            You can still receive the messages by asking for them using the commands GAME, SELF, SEE, SPECIAL and ALL.
		</documentation>
   </property>
   <property name="Async" type="boolean">
      <documentation>
			Whether to send asynchronous messages, such as HIT or AIN.
            Note that if you turn this off you will not be able to receive these messages at all.
		</documentation>
   </property>
   <!-- Extra information used by different modules of the Pogamut platform. !--><extra>
      <code/>
   </extra>
</commandobject>

=== halbich/Pogamut3/Main/PogamutUT2004/src/gb2004/messages/gbcommands/Quit.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE commandobject SYSTEM "../GBMessages.dtd">

<commandobject command="QUIT" extends="CommandMessage" name="Quit" type="Configure">
   <gbpackage name="GameBots2004"/>
   <gbpackage name="GBScenario"/>
   <gbpackage name="GameBotsAnim"/>
   <gbpackage name="GameBotsUE2"/>
   <gbpackage name="GBEmohawk"/>
   <group name="Bot"/>
   <group name="Server"/>
   <group name="Observer"/>
   <documentation>
		Will shutdown the connection and potentialy kill and remove the
		bot from a game (if sent to bot), the same can be achieved just
		by closing the connection.
	</documentation>
   <!-- List of all properties of this command. !--><!-- Extra information used by different modules of the Pogamut platform. !--><extra>
      <code/>
   </extra>
</commandobject>
